#!/bin/bash
wget -O /www/xderm/xderm-mini https://raw.githubusercontent.com/andrygibhq/xdermargon/main/xderm-mini -q
wget -O /www/xderm/index.php https://raw.githubusercontent.com/andrygibhq/xdermargon/main/index.php -q
